int server_that_can_process_requests_concurrently();
int server_that_can_only_process_requests_iteratively();
int server_that_can_process_requests_concurrently_using_child_process();
int read_from_client(int client_socket);
