int server_that_can_process_requests_concurrently_using_io_multiplexing_by_select();
int server_that_can_only_process_requests_iteratively();
int server_that_can_process_requests_concurrently_using_child_process();
int server_that_can_process_requests_concurrently_using_thread();
int read_from_client(int client_socket);
int server_that_can_process_requests_concurrently_using_thread_and_non_blocking_io();
int server_that_can_process_requests_concurrently_using_io_multiplexing_by_event_poll();
